Header header
std_msgs/String leg_name

geometry_msgs/Point walker_tip_position
geometry_msgs/Point poser_tip_position
geometry_msgs/Point model_tip_position

geometry_msgs/Point model_tip_velocity

std_msgs/Float32MultiArray joint_positions
std_msgs/Float32MultiArray joint_velocities
std_msgs/Float32MultiArray joint_efforts

std_msgs/Float64 stance_progress
std_msgs/Float64 swing_progress

geometry_msgs/Twist auto_pose

std_msgs/Float64 tip_force
std_msgs/Float64 delta_z
std_msgs/Float64 virtual_stiffness


